

distribution:
  master:
    url: "http://localhost:8080"
    name: "master"
    replication: 3
    activeNodes:
      - "Roman"
      - "Traver"
      - "Julia"
      - "Amadey"
      - "Greg"
      - "Peter"
      - "Anna"
  nodes:
    Roman:
      url: "http://localhost:7999/node"
      name: "Roman"
      queue: 300
    Traver:
      url: "http://localhost:8001/node"
      name: "Traver"
      queue: 300
    Julia:
      url: "http://localhost:8002/node"
      name: "Julia"
      queue: 300
    Amadey:
      url: "http://localhost:8003/node"
      name: "Amadey"
      queue: 300
    Greg:
      url: "http://localhost:8004/node"
      name: "Greg"
      queue: 300
    Peter:
      url: "http://localhost:8005/node"
      name: "Peter"
      queue: 300
    Anna:
      url: "http://localhost:8006/node"
      name: "Anna"
      queue: 300
